#Character generator Lists



internal_aim = ['to grow',
                'to be comfortable',
                'to self-destruct',
                'to self-express',
                'to achieve enlightenment',
                'to be at peace',
                'to gain self-esteem',
                'to be self-reliant',
                'to be safe',
                'to become wise',
                'to achieve a personal breakthrough',
                'to be in love',
                'to be perfect',
                'to survive',
                'to increase their skills',
                'to achieve emotional balance',
                'to develop a sense of identity',
                'to re-imagine themself',
                'to learn to accept things as they are'
                ]


external_aim = ['to gain power',
                'to gain wealth',
                'to gain knowledge',
                'to find their place in society',
                'to get a partner',
                'to have friends',
                'to look after their own',
                'to change the world',
                'to get basic necessities',
                'to find a missing object',
                'to find a missing person',
                'to reconnect with their roots',
                'to join a community',
                'to leave a community',
                'to make a contribution to society',
                'to create something'
                ]


quirk = ['Silent',
         'Catch phrase',
         'Huge',
         'Tiny',
         'Tattoos',
         'Unexpected virtuoso',
         'Odd gap in competence',
         'An obsession',
         'A fetish',
         'Odd dress sense',
         'Odd hairdo',
         'Horrible body stench',
         'Smells weirdly nice',
         'Thick accent',
         'Strange phobia',
         'Odd eating habits',
         'An addiction',
         'Mysterious',
         'Megalomaniacal',
         'Constant self-doubting',
         'Surrounded by rumors',
         'An obscure hatred',
         'A nervous tick',
         'A distinctive laugh',
         'A niche hobby',
         'Very tall',
         'Very short',
         'Breaks gender norms',
         'Fish out of water',
         'Land-fish',
         'Cannibalistic',
         'Incestuous',
         'Unsettlingly normal',
         'Perfectionist',
         'Haphazard',
         'Delusions of grandeur',
         'Low self-esteem',
         'Touchy about a hidden secret',
         'Over-qualified',
         'Under-qualified',
         'An unusual pet',
         'Belongs to an unexpected subculture',
         'Yo-yo dieter',
         'Paranoid',
         'Excessively cynical',
         'Pollyanna optimism',
         'Extreme philosophical beliefs',
         'An extreme daily routine',
         'Speaks a huge number of languages',
         'Very in touch with their physicality',
         'Out of touch with their body',
         'Emotionally stunted',
         'Emotionally out of control',
         'Able to sleep in the weirdest places',
         'Enjoys the pleasures of life'
        ]

moral = ['Care',
          'Fairness',
          'Loyalty',
          'Respect',
          'Purity',
          'Liberty'
    ]

vice = ['Gluttony',
        'Greed',
        'Sloth',
        'Lechery',
        'Wrath',
        'Envy',
        'Cowardice',
        'Hubris',
        'Boastfulness',
        'Despondency',
        
    ]

virtue = ['Generosity',
          'Kindness',
          'Temperance',
          'Justice',
          'Fortitude',
          'Prudence',
          'Courage',
          'Wisdom',
          'Magnificence',
          'Magnanimity',
          'Liberality',
          'Gentleness',
 
    ]

health = ['Asthma',
          'Shortsighted',
          'Nearsighted',
          'Disfigured',
          'Missing finger',
          'Missing leg',
          'Missing arm',
          'Limp',
          'Webbed toes',
          'Leper',
          'Blind',
          'Deaf',
          'Wheelchair bound',
          'Bed bound',
          'Bad teeth',
          'Obese',
          'Overweight',
          'Skinny',
          'Anorexic',
          'Anaemic',
          'Lupus',
          'Depression',
          'Anxiety',
          'Bipolar',
          'Schizophrenia',
          'PTSD',
          'ADHD',
          'OCD',
          'Terminal cancer',
          'Braces',
          'Foot troubles',
          'Bad knee',
          'Bad back',
          'Migraines',
          'An unexpected headache',
          'Fatigue',
          'Autism',
          'Restless leg',
          'Epilepsy',
          'Hair loss',
          'Scars',
          'Buff... they are really buff',
          'Lean runners physique',
          'The flexibility of a gymnast',
          'Tennis elbow',
          'A broken bone',
          'Albino',
          'Allergies',
          'Frighteningly good-looking',
          'Burn scars',
          'A broken nose',
          'Unbelievably ugly',
          'Excellent stamina',
          'Great muscular strength'
          
    ]

ethnicity = ['European',
             'Middle Eastern',
             'African',
             'Indian',
             'SE Asian',
             'E Asian',
             'Central Asian',
             'Pacific',
             'South American',
             'North American',
             'Mixed',
             'Rare minority'
    ]

role = ['law enforcement',
        'government administrator',
        'scholar',
        'rebel',
        'activist',
        'revolutionary',
        'criminal',
        'farmer',
        'merchant',
        'banker',
        'artist',
        'clergy',
        'student',
        'military',
        'politician',
        'gardener',
        'engineer',
        'accountant',
        'homemaker',
        'servant',
        'cook',
        'baker',
        'fisher',
        'lumberjack',
        'transportation',
        'waiter',
        'butler',
        'cleaner',
        'journalist',
        'factory line worker',
        'artisan',
        'hired muscle',
        'teacher',
        'musician',
        'secretary',
        'celebrity',
        'ganglord',
        'landlord',
        'entrepeneur',
        'designer',
        'bohemian',
        'social worker',
        'diplomat',
        'exile',
        'hobo',
        'inventor',
        'shopkeeper',
        'technician',
        'animal handler'
        ]
