#Famous phrases generator Lists



opening = ['Stately, plump Buck Mulligan came from the stairhead, bearing a bowl of lather on which a mirror and a razor lay crossed.',
           'riverrun, past Eve and Adam’s, from swerve of shore to bend of bay, brings us by a commodius vicus of recirculation back to Howth Castle and Environs.',
           'It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.',
           "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair.",
           'There was no possibility of taking a walk that day.',
           'I have just returned from a visit to my landlord – the solitary neighbour that I shall be troubled with.',
           'You don’t know about me, without you have read a book by the name of The Adventures of Tom Sawyer, but that ain’t no matter. That book was made by a Mr Mark Twain, and he told the truth, mainly.',
           'If you really want to hear about it, the first thing you’ll probably want to know is where I was born, and what my lousy childhood was like… and all that David Copperfield kind of crap, but I don’t feel like going into it, if you want to know the truth.',
           'Into the face of the young man who sat on the terrace of the Hotel Magnifique at Cannes there had crept a look of furtive shame, the shifty, hangdog look which announces that an Englishman is about to talk French.',
           'Last night I dreamt I went to Manderley again.',
           'It was the afternoon of my eighty-first birthday, and I was in bed with my catamite when Ali announced that the archbishop had come to see me.',
           "Take my camel, dear,’ said my Aunt Dot, as she climbed down from this animal on her return from High Mass.",
           "I write this sitting in the kitchen sink.",
           "It was a queer, sultry summer, the summer they electrocuted the Rosenbergs, and I didn’t know what I was doing in New York.",
           "If I am out of my mind, it’s all right with me, thought Moses Herzog.",
           "The snow in the mountains was melting and Bunny had been dead for several weeks before we came to understand the gravity of our situation.",
           "Squire Trelawnay, Dr Livesey, and the rest of these gentlemen having asked me to write down the whole particulars about Treasure Island, from the beginning to the end, keeping nothing back but the bearings of the island, and that only because there is still treasure not yet lifted, I take up my pen in the year of grace 17-- and go back to the time when my father kept the Admiral Benbow inn and the brown old seaman with the sabre cut first took up his lodging under our roof.",
           "Call me Ishmael.",
           "I am an invisible man.",
           "The story so far: in the beginning, the universe was created. This has made a lot of people very angry and been widely regarded as a bad move",
           "Mother died today. Or maybe, yesterday; I can't be sure.",
           "Ships at a distance have every man’s wish on board",
           "We were somewhere around Barstow on the edge of the desert when the drugs began to take hold.",
           "You better not never tell nobody but God. It’d kill your mammy.",
           "It was a bright cold day in April, and the clocks were striking thirteen.",
           "The sweat wis lashing oafay Sick Boy; he wis trembling.",
           "124 was spiteful. Full of Baby's venom.",
           "As Gregor Samsa awoke one morning from uneasy dreams he found himself transformed in his bed into a gigantic insect.",
           "Many years later, as he faced the firing squad, Colonel Aureliano Buendía was to remember that distant afternoon when his father took him to discover ice.",
           "Lolita, light of my life, fire of my loins.",
           "It was a wrong number that started it, the telephone ringing three times in the dead of night, and the voice on the other end asking for someone he was not.",
           "Every summer Lin Kong returned to Goose Village to divorce his wife, Shuyu.",
           "I am a sick man… I am a spiteful man.",
           "They shoot the white girl first.",
           "He was an old man who fished alone in a skiff in the Gulf Stream and he had gone eighty-four days now without taking a fish.",
           "It was the day my grandmother exploded.",
           "It was love at first sight.",
           "What if this young woman, who writes such bad poems, in competition with her husband, whose poems are equally bad, should stretch her remarkably long and well-made legs out before you, so that her skirt slips up to the tops of her stockings?",
           "I have never begun a novel with more misgiving.",
           "In my younger and more vulnerable years my father gave me some advice that I’ve been turning over in my mind ever since.",
           "Francis Marion Tarwater’s uncle had been dead for only half a day when the boy got too drunk to finish digging his grave and a Negro named Buford Munson, who had come to get a jug filled, had to finish it and drag the body from the breakfast table where it was still sitting and bury it in a decent and Christian way, with the sign of its Saviour at the head of the grave and enough dirt on top to keep the dogs from digging it up.",
           "Granted: I am an inmate of a mental hospital; my keeper is watching me, he never lets me out of his sight; there’s a peephole in the door, and my keeper’s eye is the shade of brown that can never see through a blue-eyed type like me.",
           "The past is a foreign country; they do things differently there.",
           "Justice?—You get justice in the next world, in this world you have the law.",
           "Vaughan died yesterday in his last car-crash.",
           "I, Tiberius Claudius Drusus Nero Germanicus This-that-and-the- other (for I shall not trouble you yet with all my titles) who was once, and not so long ago either, known to my friends and relatives and associates as “Claudius the Idiot,” or “That Claudius,” or “Claudius the Stammerer,” or “Clau-Clau-Claudius” or at best as “Poor Uncle Claudius,” am now about to write this strange history of my life; starting from my earliest childhood and continuing year by year until I reach the fateful point of change where, some eight years ago, at the age of fifty-one, I suddenly found myself caught in what I may call the “golden predicament” from which I have never since become disentangled.",
           "Of all the things that drive men to sea, the most common disaster, I’ve come to learn, is women.",
           "Psychics can see the color of time it’s blue.",
           "In the town, there were two mutes and they were always together.",
           "He – for there could be no doubt of his sex, though the fashion of the time did something to disguise it – was in the act of slicing at the head of a Moor which swung from the rafters.",
           "High, high above the North Pole, on the first day of 1969, two professors of English Literature approached each other at a combined velocity of 1200 miles per hour.",
           "When the guy with asthma finally came in from the fire escape, Parker rabbit-punched him and took his gun away.",
           "It was now lunch time and they were all sitting under the double green fly of the dining tent pretending that nothing had happened.",
           "Someone must have slandered Josef K., because one morning, without his having done anything bad, he was arrested.",
           "Where’s Papa going with that axe?’ said Fern to her mother as they were setting the table for breakfast.",
           "All children, except one, grow up.",
           "It’s a funny thing about mothers and fathers. Even when their own child is the most disgusting little blister you could ever imagine, they still think that he or she is wonderful.",
           "I still remember the day my father took me to the Cemetery of Forgotten Books for the first time.",
           "First the colours. Then the humans. That’s how I usually see things. Or at least, how I try. *** HERE IS A SMALL FACT *** You are going to die.",
           "Death is only the beginning; afterward comes the hard part.",
           "When a day that you happen to know is Wednesday starts off by sounding like Sunday, there is something seriously wrong somewhere.",
           "There was me, that is Alex, and my three droogs, that is Pete, Georgie and Dim and we sat in the Korova milkbar trying to make up our rassoodocks what to do with the evening.",
           "I am doomed to remember a boy with a wrecked voice – not because of his voice, or because he was the smallest person I ever knew, or even because he was the instrument of my mother’s death, but because he is the reason I believe in God; I am a Christian because of Owen Meany.",
           
           
           

        ]




end = ["So we beat on, boats against the current, borne back ceaselessly into the past.",
       "Then starting home, he walked toward the trees, and under them, leaving behind him the big sky, the whisper of wind voices in the wind-bent wheat.",
       "Yes, she thought, laying down her brush in extreme fatigue, I have had my vision.",
       "Whatever we had missed, we possessed together the precious, the incommunicable past.",
       "But that is another tale, and as I said in the beginning, this is just a story meant to be read in bed in an old house on a rainy night.",
       "Tomorrow, I’ll think of some way to get him back. After all, tomorrow is another day.",
       "He loved Big Brother.",
       "Don’t ever tell anybody anything. If you do, you start missing everybody.",
       "'You can trust me,' R.V. said, watching her hand. 'I’m a man of my'",
       "Up out of the lampshade, startled by the overhead light, flew a large nocturnal butterfly that began circling the room. The strains of the piano and violin rose up weakly from below.",
       "The offing was barred by a black bank of clouds, and the tranquil waterway leading to the uttermost ends of the earth flowed sombre under an overcast sky – seemed to lead into the heart of an immense darkness."
       "Everything we need that is not food or love is here in the tabloid racks. The tales of the supernatural and the extraterrestrial. The miracle vitamins, the cures for cancer, the remedies for obesity. The cults of the famous and the dead.",
       "'Excellently observed,' answered Candide; 'but we must cultivate our garden.'",
       "She was seventy-five and she was going to make some changes in her life.",
       "In a place far away from anyone or anywhere, I drifted off for a moment.",
       "As you from crimes would pardoned be, Let your indulgence set me free.",
       "and then he asked me would I yes to say yes my mountain flower and first I put my arms around him yes and drew him down to me so he could feel my breasts all perfume yes and his heart was going like mad and yes I said yes I will Yes.",
       "I got to light out for the territory ahead of the rest, because Aunt Sally she’s going to adopt me and sivilize me, and I can’t stand it. I been there before.",
       "There was the hum of bees, and the musky odor of pinks filled the air.",
       "We try, as my sister said. We try. All of us. We try.",
       "And so, as Tiny Tim observed, God bless Us, Every One!",
       "He was soon borne away by the waves, and lost in darkness and distance.",
       "Reader, I did not even have coffee with him. That much I learned in college.",
       "I’ll pray, and then I’ll sleep.",
       "She looked up and across the barn, and her lips came together and smiled mysteriously.",
       "Are there any questions?",
       "Who knows but that, on the lower frequencies, I speak for you?",
       "I wish you all a long and happy life.",
       "For an instant, everything was bathed in radiance.",
       "And Madeleine kept squinting, as though Mitchell was already far away, until finally, smiling gratefully, she answered, ‘Yes.’",
       "He runs. Ah: runs. Runs.",
       "In the deep glens where they lived all things were older than man and they hummed of mystery.",
       "She called in her soul to come and see.",
       "The creatures outside looked from pig to man, and from man to pig, and from pig to man again; but already it was impossible to say which was which.",
       "For never was a story of more woe, Than this of Juliet and her Romeo.",
       "I know myself,’ he cried, ‘but that is all.’",
       "Too much light has come out of my darkness.",
       "The man in black fled across the desert, and the gunslinger followed.",
       "I’m a liar and a cheat and a coward, but I will never, ever, rarely let a friend down.",
       "It occurred to me then that for the first time in as long as I could remember, I had absolutely no desire to log back into the OASIS.",
       "It is not often that someone comes along who is a true friend and a good writer. Charlotte was both.",
       "‘When the day shall come that we do part,’ he said softly, and turned to look at me, ‘If my last words are not 'I love you'-ye'll ken it was because I didna have time.’",
       "So, if this does end up being my last letter, please believe that things are good with me, and even when they're not, they will be soon enough. And I will believe the same about you. Love always, Charlie.",
       "When I stepped out into the bright sunlight from the darkness of the movie house, I had only two things on my mind: Paul Newman and a ride home.",
       "It is a far, far better thing that I do, than I have ever done; it is a far, far better rest that I go to than I have ever known.",
       "Or so Bill Denbrough sometimes thinks on those early mornings after dreaming, when he almost remembers his childhood, and the friends with whom he shared it.",
       "'Darling,' replied Valentine, 'has not the count just told us that all human wisdom is summed up in two words? — 'Wait and hope.'",
       "Thomas Edison's last words were: 'It's very beautiful over there.' I don't know where there is, but I believe it's somewhere, and I hope it's beautiful.",
       "And we live on. God help us, we live on.",
       "And for once I didn’t look back.",
       "P.P.S. Please if you get a chanse put some flowrs on Algernons grave in the bak yard…",
       "Now I understand that the same road was to bring us together again. Whatever we had missed, we possessed together the precious, the incommunicable past.",
       "She says nothing at all, but simply stares upward into the dark sky and watches, with sad eyes, the slow dance of the infinite stars.",
       "The class met on Tuesdays. No books were required. The subject was the meaning of life. It was taught from experience. The teaching goes on.",
       "For everything to be consummated, for me to feel less alone, I had only to wish that there be a large crowd of spectators the day of my execution and that they greet me with cries of hate.",
       "We would have been safe.",
       "I am thinking of aurochs and angels, the secret of durable pigments, prophetic sonnets, the refuge of art. And this is the only immortality you and I may share, my Lolita.",
       "But now I know that our world is no more permanent than a wave rising on the ocean. Whatever our struggles and triumphs, however we may suffer them, all too soon they bleed into a wash, just like watery ink on paper.",
       "There is ebb and flow. Leaving and coming. Flight and fall. Sing and silent. Reaching and reached.",
       "A part of me lies buried in lace and roses on a riverbank in France — a part of me is broken off forever. A part of me will always be unflyable, stuck in the climb.",
       "And that might be the subject of a new story but our present story is over.",
       "I could hear my heart beating. I could hear everyone’s heart. I could hear the human noise we sat there making, not one of us moving, not even when the room went dark.",
       "He turned out the light and went into Jem's room. He would be there all night, and he would be there when Jem waked up in the morning.",
       "But for them it was only the beginning of the real story. All their life in this world and all their adventures in Narnia had only been the cover and the title page: now at last they were beginning Chapter One of the Great Story which no one on earth has read: which goes on for ever: in which every chapter is better than the one before.",
       "They had an ordinary life, full of ordinary things — if love can ever be called that.",
       "And now that you don’t have to be perfect, you can be good.",
       "I just waited a bit, then turned back to the car, to drive off to wherever it was I was supposed to be.",
       "'Stories are light,' Gregory the jailer told Despereaux. Reader, I hope you have found some light here.",
       "I don’t have anything else to add. I just wanted to make sure I had the last word. I think I’ve earned that.",
       "But I don't think us feel old at all. And us so happy. Matter of fact, I think this the youngest us ever felt. Amen.",
       
       
       
    ]

