#Scene generator Lists


# verbs (it is about X)
event = ['seeing',
         'hearing',
         'smelling',
         'touching',
         'tasting',
         'giving birth',
         'dying',
         'stealing',
         'gifting',
         'plotting',
         'confessing',
         'surviving',
         'suffering',
         'missing',
         'hitting',
         'running',
         'hiding',
         'kidnapping',
         'escaping',
         'struggling',
         'relaxing',
         'fearing',
         'trusting',
         'threatening',
         'comforting',
         'arriving',
         'leaving',
         'breaking',
         'repairing',
         'being ill',
         'healing',
         'losing',
         'winning',
         'being humiliated',
         'being accepted',
         'gaining',
         'losing',
         'being praised',
         'being insulted',
         'conquering',
         'being conquered',
         'joining',
         'seperating',
         'mourning',
         'celebrating',
         'encountering',
         'discovering',
         'destroying',
         'creating',
         'buying',
         'selling',
         'retrieving',
         'disposing',
         'helping',
         'hindering',
         'fixing',
         'damaging',
         'restoring',
         'planting',
         'uprooting',
         'growing',
         'decaying',
         'freeing',
         'trapping',
         'submitting',
         'protesting',
         'expressing love',
         'expressing hate',
         'choosing the road less travelled',
         'conforming',
         'caring',
         'abusing',
         'fighting',
         'embracing',
         'overcoming',
         'underachieving',
         'achieving enlightenment',
         'confusion',
         'peace making',
         'declaring war'
         ]


speed = ['super fast',
         'fast',
         'fairly quick',
         'fairly slow',
         'slow',
         'super slow',
         ]

choose = ['denial',
          'returning to the past',
          'forging a new path',
          'fleeing',
          'tactical retreat',
          'melting down',
          'self-anaesthetizing',
          'fighting',
          'giving up',
          'compromising',
          'transcending',
          'taking advantage',
          'screwing someone over',
          'screwing with someone',
          'betrayal',
          'keeping a promise',
          'reforming',
          'delaying',
          'improvising',
          'careful planning',
          'accepting the situation',
          'denying the past',
          'fighting the future',
          'following someone else',
          'going rouge',
          'following the group',
          'obedience',
          'disobedience',
          'utter insanity',
          'the rational path',
          'the emotional path',
          'the instinctive path',
          'following tradition',
          'an innovative solution'
          
    ]

twist = ['offending an ally',
          'triggering an timebomb',
          'triggering a trap',
          'empowering an enemy',
          'losing the prize',
          'learning the price was too high',
          'learning the prize is a curse',
          'discovering a connection with the enemy',
          'losing something trivial yet essential',
          'public humiliation',
          'waking the monsters',
          'a fork in the road',
          'mutiny by those below them',
          'an urgent need to flee',
          'accidental confession',
          'revealing a hidden villain',
          'getting the right thing in the wrong way',
          'uncovering a lie',
          'a serious injury',
          'those who were mistreated biting back',
          'revealing someones true identity',
          'revealing your own unknown true identity',
          'becoming the victim of ones own schemes',
          'a Freudian slip',
          'the first of a thousand cuts',
    ]

time = ['midnight',
        'small hours of the night',  
         'predawn',
         'dawn',
         'morning',
         'noon',
         'afternoon',
         'evening',
         'dusk',
         'night',
         'late night',
         ]

affect = ['pleasant',
          'unpleasant']

temp = ['hot',
        'cold'
        ]

hum = ['wet',
       'dry'
       ]

smell = ['odorous',
       'no smell'
       ]

noise = ['loud',
       'quiet'
       ]

light = ['dark',
       'bright'
       ]

space = ['open',
         'cramped'
         ]

color = ['black',
         'white',
         'red',
         'blue',
         'yellow',
         'grey',
         'purple',
         'green',
         'orange',
         'brown'
       ]

quirk = ['an animal',
         'machinery',
         'plants',
         'artwork',
         'dirty dishes',
         'an item of clothing',
         'books',
         'scrawled notes',
         'something broken',
         'something priceless',
         'something disgusting',
         'something missing',
         'flowers',
         'food',
         'signs of someones presence',
         'a glass of water',
         'an embaressing moment',
         'unusual weather',
         'something that doesnt belong',
         'an unexpected danger',
         'an unexpected blessing',
         'something embarressing',
         'a long lost treasure',
         'stolen goods',
         'shoes',
         'a bag',
         'a pot',
         'cooking utensils',
         'a raincoat',
         'cleaning supplies',
         'a to do list',
         'esoteric symbols written on the ground',
         'a mask',
         'a locked chest'
         
        ]

