#Solarpunk generator Lists


# Utopian aspect is
utopia = ['Post-scarcity',
          'Equality and equity',
          'Inclusivity',
          'Sustainable economics',
          'Harmony with nature',
          'Sustainable technology',
          'Clean energy',
          'Care for future generations',
          'Psychological wellbeing',
          'Active citizenship',
          'Environmental restoration',
          'Maker culture',
          'Decentralized infrastructure',
          'Local solutions',
          'Autonomous functioning systems',
          'Balance within planetary limits',
          'Cooperative ownership',
          'Democracy',
          'World peace',
          'Accessible commons',
          'Good science',
          'Good spirituality/philosophy',
          'Cooperation between cultures',
          'A good educational system',
          'A good justice system',
          'A good political system',
          'Circular economy',
          'Gift economy',
          'Limiting and adapting to climate change',
          'Rewilding',
          'Reconcilliation made for past crimes',
          'New technological developments',
          'New forms of social organisation',
          'Healthy communities',
          'Healthy independance',
          'Decontaiminating pollution',
          'Healthy parenting',
          'Healthy communication',
          'Healthy relationships',
          'The best library ever',
          'Functional public transport',
          'Healthy social media',
          'Appropriate technology',
          'Accessibility for disabled people',
          'Minority but not marginalized',
          'Everyone gets enough sustenance',
          'Everyone gets enough safety',
          'Everyone gets enough love',
          'Everyone gets enough recreation',
          'Everyone gets enough community',
          'Everyone gets enough creativity',
          'Everyone gets enough autonomy',
          'Everyone gets enough meaning'
          
          
         ]

# Punk aspect is
punk = ['Rebellion',
        'Post-capitalism',
        'Anti-hierarchy',
        'Anti-authoritarian',
        'Counter-culture',
        'Decolonialism',
        'Escaping the death cult',
        'Against nihilism',
        'Against doomerism',
        'Against apathy',
        'Activism',
        'Against exclusion',
        'Against oppression',
        'Against racism',
        'Against sexism',
        'Against militarism',
        'Guerilla gardening',
        'Movement organising',
        'Protest',
        'Direct action',
        'Against throw-away culture',
        'Against cynicism',
        'Against greenwashing',
        'Against survivalism',
        'Against moralistic judgement',
        'Against zero-sum thinking',
        'Against black and white thinking',
        'Against violence',
        'Against self-hatred',
        'Against manipulation and control',
        'Against rigid conformity',
        'Against mass incarceration',
        'Monkeywrenching',
        'Against car-dependence',
        'Against consumerism',
        'Against survelliance',
        'Against advertising',
        'Against obscene wealth inequality',
        'Mass movements for a better world',
        'The power of small acts',
        'Against weapons of mass destruction',
        'Against fetishizing technology',
        
        

        ]

# The hopeful mood is about
mood = ['Creativity',
        'Ingenuity',
        'Generativity',
        'Wonder',
        'Meaning',
        'Loving the world',
        'Compassion',
        'Acceptance',
        'Beauty',
        'Peace',
        'Hope',
        'Healing',
        'Excitement',
        'Possibility',
        'Wisdom',
        'Balance',
        'Excellence',
        'Health',
        'Laughter'
        ]

# The aesthetic is
aesthetic = [ 'Age of sail/frontier life',
              'Creative re-use/Jugaad innovation',
              'Art Noveau',
              'Hayao Miyazaki',
              'High-tech backends with elegant output',
              'African',
              'Neo-Mayan',
              'Indigenous',
              'Asian',
              ]


# A trope to play with is
# Note: some tropes are kinda stupid, but hey, play with them!
trope = ['Gardens are a human right',
         'Urban green space is everywhere now',
         'Urban agriculture is how we eat now',
         'Skyscrapers, but now with more plants',
         'Airships',
         'Lets do permaculture, absolutely everywhere',
         'Indigenous people have the answer',
         'Mad-Max, but now with more hydroponics',
         'Home-made clothing',
         'Wild food foraging',
         'Bicycles',
         'Solar panels',
         'Clothes, but now with plants on them',
         'DIY',
         'Animals are our friends now',
         'Plants are our friends now',
         'Everything is made of mushrooms now',
         'Mending your own stuff',
         'The joys of home cooking',
         'Our independant fashion sense will blow your mind',
         'Recycling and upcycling',
         'Windmills',
         'Unexpected uses for clay pots',
         'Reviving ancient methods',
         'A really big tree',
         'Relocating wildlife because of climate change',
         'The quest for immortality',
         'Dropping out of society',
         'Malevolent rich people',
         'The downsides of being a violent terrorist',
         'Maybe explosives is the answer to our lives problems?',
         'We all chained ourselves to something to make a point',
         'Sticking it to the Man',
         'Billionaires... in spaaaaace!',
         'Moving to space somehow makes sense now because of how much we damaged Earth', 
         'Environmental disaster is a bad place to live',
         'Super-Venice',
         'Re-introducing wild species (possibly via airborne space invasion)',
         'Domes. We all live in domes now.',
         'Archaeology of the Before-Time. Why were the ancestors so foolish?',
         'Robots, but made with bamboo and string and stuff',
         'Plants you can talk to, and they might talk back',
         'Terraforming other planets',
         'Noahs Ark style eco-sanctuary',
         'That one place, in that secret valley, where everything is perfect.',
         'Mother Earth gets revenge',
         'Hacking the system (under a GNU public license)',
         'Finding a way for the unused surplus of the rich to be accessed by the excluded poor',
         'We all live in underground bunkers now',
         'Sky cities',
         'Underwater cities',
         'Floating cities',
         'Mutants',
         'Cybernetic implants',
         'Being in awe of the technology of the Before-Time. How does it work Daddy? No one knows Son...',
         'Nature reclaiming civilisation',
         'We all live inside asteroids now',
         'Wise aliens who sorted all this crap out aeons ago',
         'Over-application of solar technology',
         'We all play pan flutes now. Come join the drumming circle.',
         'Nature is toxic now. Please stay within your safety bubble.',
         'We have one type of weather now - eternal drought.',
         'We have one type of weather now - permanent superstorms.',
         'We have one type of weather now - ice. We froze everything somehow.',
         'Cybernetic trees',
         'We are all scavengers now, living in the ruins of the Before-Time.',
         'This is so screwed up we need to invent time-travel.',
         'Old person meets young person. Sparks and/or wisdom fly.',
         'Everything is falling into the sea, like, everything.',
         'Climate change means the basic necessities of life are hard to get now',
         'Genetically engineered eco-organisms (possibly a large aggressive conservation minded insect)',
         'We all live in a biodome now',
         'We all dress like elves from LOTR now',
         'You can fix anything with herbs',
         'Capitalism... in spaaaace!',
         'City A does X, but city B does Y.',
         'Naked hotpools are the accepted recreation now.',
         'Get in a stand off with the riot police.',
         'Never use the verb "to be" when describing people.',
         'Never use financial language for non-financial things e.g. spend time.',
         
         
    
         
         ]


