#Story generator Lists


#nouns, verbs "about X"
event = ['a doppelganger',
         'a dead body',
         'a theft',
         'a heist',
         'plotting murder',
         'a survival emergency',
         'a missing person',
         'running away',
         'a kidnapping',
         'a succession struggle',
         'impending doom',
         'impending utopia',
         'a revolution',
         'a desired power',
         'a ransom',
         'arriving at a new place',
         'a break up',
         'a health crisis',
         'a loss of wealth',
         'a loss of status',
         'a gain of wealth',
         'a gain of status',
         'a wedding',
         'a funeral',
         'a new relationship',
         'discovering an object',
         'destroying an object',
         'a purchase',
         'a sale',
         'a debt',
         'retrieving something',
         'disposing of something',
         'just trying to get by',
         'discovering the real truth',
         'loss of innocence',
         'learning new ways',
         'the end of an era',
         'new beginnings',
         'a crime',
         'vengenance',
         'true heroism',
         'true villany'
         
         ]


theme = ['Power',
         'Money',
         'Change vs Tradition',
         'Chaos vs Order',
         'The circle of life',
         'Coming of age',
         'Friendship',
         'Family',
         'Disillusionment',
         'False dreams',
         'Promises',
         'Love',
         'Faith vs Doubt',
         'Fate vs Free will',
         'Failure',
         'Good vs Evil',
         'Downfall',
         'Justice',
         'Identity',
         'Immortality',
         'Individual vs Society',
         'Knowledge vs Ignorance',
         'Hope',
         'Truth',
         'Trust',
         'Innocence',
         'Sacrifice',
         'Man vs nature',
         'Nationalism',
         'Oppression',
         'Corruption',
         'Progress',
         'Discovery',
         'Religion',
         'Gender',
         'Self-awareness',
         'Technology',
         'Temptation',
         'Vanity',
         'Vulnerability',
         'Survival',
         'Wisdom'
    ]

mice = ["a Setting",
        "an Idea",
        "a Character",
        "an Event"
        ]

speed = ['very short',
         'short',
         'long',
         'very long'
         ]

plot = ['Hamlet (flat)',
        'Rags to riches (rise)',
        'Riches to rags (fall)',
        'Man-in-hole (fall-rise)',
        'Icarus (rise-fall)',
        'Cinderella (rise-fall-rise)',
        'Oedipus (fall-rise-fall)'
    ]

genre = ['Crime',
         'Mystery',
         'Detective',
         'Adventure',
         'Thriller',
         'Fantasy',
         'Sci-fi',
         'Western',
         'Historical',
         'Romance',
         'Horror',
         'Contemporary',
         'Humor'
    ]

#adjective (told in X style)
style = ['an opinionated',
         'an objective',
         'a poetic',
         'a transparent',
         'an intimate',
         'an aloof',
         'a verbose',
         'a snappy',
         'a blunt',
         'a convoluted',
         'a sarcastic',
         'an honest',
         'an unreliable',
         'a childlike',
         'a mature',
         'a detailed',
         'a broad',
         'a slow',
         'a fast',
         'a curious',
         'an emotional',
         'a dispassionate',
         'a stream-of-consciousness',
         'a colloquial',
         'a Literary',
         'a dreamy',
         'a matter-of-fact',
         'a surreal',
         'a vigilant',
         'an ecstatic',
         'an admiring',
         'a terrified',
         'an amazed',
         'a grieving',
         'a loathing',
         'an enraged',
         'an annoyed',
         'an interested',
         'a serene',
         'an accepting',
         'an apprehensive',
         'a distracted',
         'a pensive',
         'a frustrated',
         'an irritated',
         'an anticipatory',
         'a disgusted',
         'a calm',
         'a relfective',
         'a reactive',
         'a loving'
    ]

#add '2nd person' etc if you are a masochist
pov = ['1st person',
       '3rd person limited',
       '3rd person omniscient',
       '3rd person objective'
    ]

#add 'future tense' etc if you are a masochist
tense = ['present tense', 'past tense']
         
